// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package authdb

import (
	"time"
)

type Session struct {
	ID           int32     `json:"id"`
	UserID       int32     `json:"user_id"`
	SessionToken string    `json:"session_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID             int32     `json:"id"`
	Username       string    `json:"username"`
	PasswordHash   string    `json:"password_hash"`
	Role           string    `json:"role"`
	IpRestrictions []string  `json:"ip_restrictions"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
